// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Steamnt.Api.Data;

#nullable disable

namespace Steamnt.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524162517_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Steamnt.Api.Models.Developer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StudioName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Developers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "México",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Empresa dedicada al desarrollo de videojuegos solamente para Steamnt.",
                            IsActive = true,
                            StudioName = "Café Studios",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Steamnt.Api.Models.Download", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DownloadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Downloads");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DownloadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Steamnt.Api.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DeveloperId")
                        .HasColumnType("int");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pues Pokémon",
                            DeveloperId = 1,
                            DownloadUrl = "https://example.com/pokemon-region-sonora.zip",
                            ImageUrl = "https://via.placeholder.com/400x250?text=Pokemon+Region+Sonora",
                            IsPublished = true,
                            Price = 10.00m,
                            ReleaseDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pokémon"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pues Minecraft",
                            DeveloperId = 1,
                            DownloadUrl = "https://example.com/minecraft.zip",
                            ImageUrl = "https://via.placeholder.com/400x250?text=Minecraft",
                            IsPublished = true,
                            Price = 35.50m,
                            ReleaseDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Minecraft"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Juego de aventura donde debes capturar a Dora antes de que sea demasiado tarde y llegue a otro continente.",
                            DeveloperId = 1,
                            DownloadUrl = "https://example.com/captura-a-dora.zip",
                            ImageUrl = "https://via.placeholder.com/400x250?text=Captura+a+Dora",
                            IsPublished = true,
                            Price = 3.99m,
                            ReleaseDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Captura a Dora la Exploradora"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Explora Hermosillo, visita Pueblitos, sobrevive al calor y a los baches.",
                            DeveloperId = 1,
                            DownloadUrl = "https://example.com/paseo-hermosillo.zip",
                            ImageUrl = "https://via.placeholder.com/400x250?text=Un+Paseo+por+Hermosillo",
                            IsPublished = true,
                            Price = 24.99m,
                            ReleaseDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Un Paseo por Hermosillo"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Juego de mundo abierto donde recorres Obregón y tratas de no quedarte sin gasolina.",
                            DeveloperId = 1,
                            DownloadUrl = "https://example.com/gta-obregon.zip",
                            ImageUrl = "https://via.placeholder.com/400x250?text=GTA+Obregon",
                            IsPublished = true,
                            Price = 35.50m,
                            ReleaseDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "GTA Obregón"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Intenta entrar al ITH mientras se presenta una huelga por el precio de los papaboneless",
                            DeveloperId = 1,
                            DownloadUrl = "https://example.com/huelga-ith.zip",
                            ImageUrl = "https://via.placeholder.com/400x250?text=huelga+ITH",
                            IsPublished = true,
                            Price = 34.99m,
                            ReleaseDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "ITH en Huelga"
                        });
                });

            modelBuilder.Entity("Steamnt.Api.Models.GameGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("GameId", "GenreId")
                        .IsUnique();

                    b.ToTable("GameGenres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GameId = 1,
                            GenreId = 3
                        },
                        new
                        {
                            Id = 2,
                            GameId = 1,
                            GenreId = 2
                        },
                        new
                        {
                            Id = 3,
                            GameId = 2,
                            GenreId = 2
                        },
                        new
                        {
                            Id = 4,
                            GameId = 2,
                            GenreId = 5
                        },
                        new
                        {
                            Id = 5,
                            GameId = 3,
                            GenreId = 1
                        },
                        new
                        {
                            Id = 6,
                            GameId = 3,
                            GenreId = 2
                        },
                        new
                        {
                            Id = 7,
                            GameId = 4,
                            GenreId = 2
                        },
                        new
                        {
                            Id = 8,
                            GameId = 4,
                            GenreId = 5
                        },
                        new
                        {
                            Id = 9,
                            GameId = 5,
                            GenreId = 1
                        },
                        new
                        {
                            Id = 10,
                            GameId = 5,
                            GenreId = 2
                        },
                        new
                        {
                            Id = 11,
                            GameId = 6,
                            GenreId = 4
                        },
                        new
                        {
                            Id = 12,
                            GameId = 6,
                            GenreId = 2
                        });
                });

            modelBuilder.Entity("Steamnt.Api.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Juegos con combate, movimiento rápido o desafíos intensos.",
                            IsActive = true,
                            Name = "Acción"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Juegos enfocados en exploración e historia.",
                            IsActive = true,
                            Name = "Aventura"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Juegos con progresión de personaje y toma de decisiones.",
                            IsActive = true,
                            Name = "RPG"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Juegos diseñados para causar tensión o miedo.",
                            IsActive = true,
                            Name = "Terror"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Juegos desarrollados por estudios pequeños o independientes.",
                            IsActive = true,
                            Name = "Indie"
                        });
                });

            modelBuilder.Entity("Steamnt.Api.Models.LibraryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId", "GameId")
                        .IsUnique();

                    b.ToTable("LibraryItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Steamnt.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "usuario@steamnt.com",
                            Name = "Usuario",
                            PasswordHash = "123456",
                            Role = "User"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "developer@steamnt.com",
                            Name = "Desarrollador",
                            PasswordHash = "123456",
                            Role = "Developer"
                        });
                });

            modelBuilder.Entity("Steamnt.Api.Models.Developer", b =>
                {
                    b.HasOne("Steamnt.Api.Models.User", "User")
                        .WithOne("DeveloperProfile")
                        .HasForeignKey("Steamnt.Api.Models.Developer", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Steamnt.Api.Models.Download", b =>
                {
                    b.HasOne("Steamnt.Api.Models.Game", "Game")
                        .WithMany("Downloads")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Steamnt.Api.Models.User", "User")
                        .WithMany("Downloads")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Steamnt.Api.Models.Game", b =>
                {
                    b.HasOne("Steamnt.Api.Models.Developer", "Developer")
                        .WithMany("Games")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("Steamnt.Api.Models.GameGenre", b =>
                {
                    b.HasOne("Steamnt.Api.Models.Game", "Game")
                        .WithMany("GameGenres")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Steamnt.Api.Models.Genre", "Genre")
                        .WithMany("GameGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Steamnt.Api.Models.LibraryItem", b =>
                {
                    b.HasOne("Steamnt.Api.Models.Game", "Game")
                        .WithMany("LibraryItems")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Steamnt.Api.Models.User", "User")
                        .WithMany("LibraryItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Steamnt.Api.Models.Developer", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("Steamnt.Api.Models.Game", b =>
                {
                    b.Navigation("Downloads");

                    b.Navigation("GameGenres");

                    b.Navigation("LibraryItems");
                });

            modelBuilder.Entity("Steamnt.Api.Models.Genre", b =>
                {
                    b.Navigation("GameGenres");
                });

            modelBuilder.Entity("Steamnt.Api.Models.User", b =>
                {
                    b.Navigation("DeveloperProfile");

                    b.Navigation("Downloads");

                    b.Navigation("LibraryItems");
                });
#pragma warning restore 612, 618
        }
    }
}
